# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Test"
concurrency:
  group: "test"
on:
  workflow_dispatch:
jobs:
  set:
    permissions:
      contents: "read"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v5"
      - name: "Setup Deno"
        uses: "denoland/setup-deno@v2"
        with:
          deno-version: "^2.4.5"
      - name: "Set"
        id: "set"
        shell: "pwsh"
        env:
          TEST_GHPAT: "${{secrets.TEST_GHPAT}}"
        run: |-
          [String]$SampleValue = (New-Guid).Guid.ToUpper() -ireplace '-', ''
          Add-Content -LiteralPath $Env:GITHUB_OUTPUT -Value "value=$($SampleValue)" -Confirm:$False -Encoding 'UTF8NoBOM'
          [PSCustomObject]$PublicKey = Invoke-RestMethod -Uri "https://api.github.com/repos/$($Env:GITHUB_REPOSITORY)/actions/secrets/public-key" -Headers @{
            Accept = 'application/vnd.github+json';
            Authorization = "Bearer $($Env:TEST_GHPAT)";
            'X-GitHub-Api-Version' = '2022-11-28';
          } -Method 'Get'
          [String]$SampleEncrypted = (
            deno eval "import { GitHubSodiumSealer } from `"./basic.ts`"; console.log(new GitHubSodiumSealer(`"$($PublicKey.key)`").encrypt(`"$($SampleValue)`"));" |
              Join-String -Separator "`n"
          ).Trim()
          Invoke-RestMethod -Uri "https://api.github.com/repos/$($Env:GITHUB_REPOSITORY)/actions/secrets/TEST_VALUE" -Headers @{
            Accept = 'application/vnd.github+json';
            'Content-Type' = 'application/json';
            Authorization = "Bearer $($Env:TEST_GHPAT)";
            'X-GitHub-Api-Version' = '2022-11-28';
          } -Method 'Put' -Body (ConvertTo-Json -InputObject @{
            encrypted_value = $SampleEncrypted;
            key_id = $PublicKey.key_id;
          } -Depth 100 -Compress)
    outputs:
      value: "${{steps.set.outputs.value}}"
  get:
    needs:
      - "set"
    permissions:
      contents: "read"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Get"
        shell: "pwsh"
        env:
          TEST_VALUE_FROM: "${{secrets.TEST_VALUE}}"
          TEST_VALUE_ORIGINAL: "${{needs.set.outputs.value}}"
        run: |-
          If ($Env:TEST_VALUE_FROM -cne $Env:TEST_VALUE_ORIGINAL) {
            Exit 1
          }
