# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Test - Get"
on:
  workflow_dispatch:
    inputs:
      value:
        type: "string"
        description: "Value."
        required: true
jobs:
  get:
    permissions:
      contents: "read"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Get"
        shell: "pwsh"
        env:
          TEST_VALUE_LIBSODIUM: "${{secrets.TEST_LIBSODIUM_VALUE}}"
          TEST_VALUE_ORIGINAL: "${{inputs.value}}"
          TEST_VALUE_TWEETSODIUM: "${{secrets.TEST_TWEETSODIUM_VALUE}}"
        run: |-
          $ErrorActionPreference = 'Stop'
          $PSNativeCommandUseErrorActionPreference = $True
          Add-Content -LiteralPath $Env:GITHUB_STEP_SUMMARY -Value @"
          | **Name** | **Result** |
          |:--|:-:|
          | LibSodium | $(($Env:TEST_VALUE_LIBSODIUM -ceq $Env:TEST_VALUE_ORIGINAL) ? '✔️' : '❌') |
          | TweetSodium | $(($Env:TEST_VALUE_TWEETSODIUM -ceq $Env:TEST_VALUE_ORIGINAL) ? '✔️' : '❌') |
          "@
